### ISSUE TITLE
Scan page shows negative resistances

### ISSUE THREAD

**Issue by johnp789** [mooshim/Mooshimeter-AndroidApp#19]
In the scan page, if resistance is shown and nothing is connected to the leads, the resistance momentarily shows OVERLOAD, but then it shows values around -5600 ohms (negative values).

**Comment by jwhong** [comment]
Hi John,

Can you verify the version of the app you're running?

**Comment by johnp789** [comment]
I have version 1.0.17 (444) on a 2013 Moto X  with Android 4.4.4.

**Comment by jwhong** [comment]
Very helpful, thanks.  One more thing:  look at the back Mooshimeter and
find the text that says "Mooshimeter Rev*" followed by a date - can you
write whether it says RevI or RevH?

**Comment by johnp789** [comment]
Mooshimeter RevI 04/2015.  It's from the second manufacturing run.

**Comment by jwhong** [comment]
Calculation of readings is unified, no more discrepency in beta
