### ISSUE TITLE
Broadcast intents

### ISSUE THREAD

**Issue by jwhong** [mooshim/Mooshimeter-AndroidApp#31]
Have the Mooshimeter app broadcast intents (in Android) so that other apps can record and process the data without having to interact with the Mooshimeter app itself.

Status: Implemented by Duane for Android, awaiting merge to main app.

**Comment by phedders** [comment]
:+1: Very happy about this! Many thanks James and Duane! Now I can send data to my watch :)

**Comment by jwhong** [comment]
Merged a while ago
