### ISSUE TITLE
In lowest resistance range, the app displays a reading instead of "out of range" when the probes are open

### ISSUE THREAD

**Issue by jwhong** [mooshim/Mooshimeter-AndroidApp#39]

**Comment by jwhong** [comment]
Fixed on beta branch

**Comment by mirko12** [comment]
still wrong in 1k and 1M range. see #53

**Comment by jwhong** [comment]
Thank you mirko - you were right.  I think I got it with this commit: https://github.com/mooshim/Mooshimeter-AndroidApp/commit/6e2cdcbeb2107e9bd46e099b7bfa754d08ebd8fc

Sorry for the premature close and thanks again
