### ISSUE TITLE
Internal temperature bug

### ISSUE THREAD

**Issue by jwhong** [mooshim/Mooshimeter-AndroidApp#9]
Greg writes:

I did notice a possible bug when reading the internal temperature.

Set channel 1 to Amps DC and channel 2 to resistance.
Short channel 2 leads together for a few seconds so resistance reads zero and then open leads again.
Now switch channel 1 to INT and you get OVERLOAD.
Switch channel 2 to INT and channel 2 reads correct temperature.
Toggle Channel 1 a few times and it will read normally as well for INT.

Now if you repeat the above procedure but initially set channel 1 to Amps AC you will get a internal temp reading of -271 or 0×000000.
Also you need to go back to Amps DC before channel 1 can correctly read internal temperature.

I am using a Nexus 7 (2012) with CM11.0 (Kitkat 4.4.4)

**Comment by electrokean** [comment]
This isn't an Android specific issue.  I saw the same readings using the iphone app (iPhone 4S running iOS 8) although I didn't work out the exact steps to reproduce.
